# Generated by Django 5.2.7 on 2025-12-18 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellbeingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("dominant_emotion", models.CharField(max_length=50)),
                ("dominant_emotion_ratio", models.FloatField()),
                ("emotion_counts", models.JSONField()),
                ("avg_movement", models.FloatField()),
            ],
        ),
    ]
