# Generated by Django 5.2.7 on 2025-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_wellbeinglog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellbeinglog",
            name="eye_blink_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wellbeinglog",
            name="fatigue_level",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="wellbeinglog",
            name="focus_level",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="wellbeinglog",
            name="head_pose",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wellbeinglog",
            name="pose",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
