# Generated by Django 5.2.7 on 2025-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_wellbeinglog_eye_blink_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellbeinglog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="wellbeing_images/%Y/%m/%d/"
            ),
        ),
    ]
